language: go

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libgit2-dev
go:
  - 1.6
  - 1.7.x
  - tip

before_script:
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u github.com/golang/lint/golint

script:
  - make ensure_modules
  - make compliant && git diff --exit-code
  - make
  - make check
